apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: spring-boot-docker
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /.*
  service:
    host: spring-boot-docker
    name: spring-boot-docker
    port: 8080
